### ISSUE TITLE
Question about num_iterations parameter in connected_components_with_gradients

### ISSUE THREAD

**Issue by aymuos15** [BrainImageAnalysis/instance-loss#3]
Based on what has it been set to 75?

**Comment by febrianrachmadi** [comment]
Hi,

This is explained in the paper's Appendix B, written below.

> If N  is sufficiently large, then, after the iterations, each connected component (instance) will have a unique integer ID. Based on our experiments, a good trade-off between the number of iterations (N) and the computation complexity is setting N equals to half the image’s maximum resolution. For example, for an image with 512 × 128 resolution, it would be 512 / 2 = 256.

Thus, 75 is just a default number for N.

**Comment by aymuos15** [comment]
Thank you very much!
